name: "Pull Request Labeler"
on:
- pull_request_target

permissions:
  contents: read

jobs:
  labeler:
    permissions:
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Label pull request
        uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yml
